# Generated by Django 4.2.7 on 2026-06-11 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('role', models.CharField(choices=[('ADMIN', '管理员'), ('FIELD_WORKER', '现场人员'), ('OBSERVER', '观察员')], default='OBSERVER', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否可登录后台')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='事件标题')),
                ('description', models.TextField(verbose_name='事件描述')),
                ('severity', models.CharField(choices=[('LOW', '低'), ('MEDIUM', '中'), ('HIGH', '高'), ('CRITICAL', '紧急')], default='MEDIUM', max_length=20, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('OPEN', '待处理'), ('IN_PROGRESS', '处理中'), ('RESOLVED', '已解决'), ('CLOSED', '已关闭')], default='OPEN', max_length=20, verbose_name='处理状态')),
                ('incident_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发生时间')),
                ('resolution', models.TextField(blank=True, verbose_name='处理方案')),
                ('resolved_time', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_incidents', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '异常事件',
                'verbose_name_plural': '异常事件',
                'ordering': ['-incident_time'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='巡检项编码')),
                ('name', models.CharField(max_length=100, verbose_name='巡检项名称')),
                ('value_type', models.CharField(choices=[('NUMERIC', '数值型'), ('BOOLEAN', '布尔型'), ('TEXT', '文本型'), ('CHOICE', '选择型')], default='NUMERIC', max_length=20, verbose_name='值类型')),
                ('unit', models.CharField(choices=[('°C', '摄氏度'), ('%', '百分比'), ('kg', '千克'), ('L', '升'), ('ppm', '百万分比'), ('', '无'), ('CUSTOM', '自定义')], default='', max_length=20, verbose_name='单位')),
                ('custom_unit', models.CharField(blank=True, max_length=20, verbose_name='自定义单位')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='正常值下限')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='正常值上限')),
                ('choice_options', models.JSONField(blank=True, default=list, verbose_name='选择项列表')),
                ('description', models.TextField(blank=True, verbose_name='巡检说明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '巡检项',
                'verbose_name_plural': '巡检项',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='栏区编号')),
                ('name', models.CharField(max_length=100, verbose_name='栏区名称')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='位置描述')),
                ('livestock_type', models.CharField(max_length=50, verbose_name='养殖类型')),
                ('capacity', models.IntegerField(default=0, verbose_name='容量')),
                ('current_count', models.IntegerField(default=0, verbose_name='当前数量')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '栏区',
                'verbose_name_plural': '栏区',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='巡检时间')),
                ('remarks', models.TextField(blank=True, verbose_name='巡检备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_records', to=settings.AUTH_USER_MODEL, verbose_name='巡检人')),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_records', to='api.pen', verbose_name='栏区')),
            ],
            options={
                'verbose_name': '巡检记录',
                'verbose_name_plural': '巡检记录',
                'ordering': ['-inspection_time'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItemValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.FloatField(blank=True, null=True, verbose_name='数值')),
                ('boolean_value', models.BooleanField(blank=True, null=True, verbose_name='布尔值')),
                ('text_value', models.TextField(blank=True, verbose_name='文本值')),
                ('is_abnormal', models.BooleanField(default=False, verbose_name='是否异常')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('inspection_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='api.inspectionitem', verbose_name='巡检项')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_values', to='api.inspectionrecord', verbose_name='巡检记录')),
            ],
            options={
                'verbose_name': '巡检项值',
                'verbose_name_plural': '巡检项值',
                'ordering': ['record', 'inspection_item__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('OPEN', '待处理'), ('IN_PROGRESS', '处理中'), ('RESOLVED', '已解决'), ('CLOSED', '已关闭')], max_length=20, verbose_name='原状态')),
                ('new_status', models.CharField(choices=[('OPEN', '待处理'), ('IN_PROGRESS', '处理中'), ('RESOLVED', '已解决'), ('CLOSED', '已关闭')], max_length=20, verbose_name='新状态')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='api.incident', verbose_name='异常事件')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_updates', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '事件更新记录',
                'verbose_name_plural': '事件更新记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='inspection_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='api.inspectionrecord', verbose_name='关联巡检记录'),
        ),
        migrations.AddField(
            model_name='incident',
            name='pen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='api.pen', verbose_name='栏区'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL, verbose_name='上报人'),
        ),
        migrations.CreateModel(
            name='FeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_type', models.CharField(max_length=100, verbose_name='饲料类型')),
                ('feed_amount', models.FloatField(verbose_name='投喂量(kg)')),
                ('feeding_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='喂养时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_records', to=settings.AUTH_USER_MODEL, verbose_name='喂养人')),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_records', to='api.pen', verbose_name='栏区')),
            ],
            options={
                'verbose_name': '喂养记录',
                'verbose_name_plural': '喂养记录',
                'ordering': ['-feeding_time'],
            },
        ),
        migrations.CreateModel(
            name='CleaningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning_type', models.CharField(choices=[('DAILY', '日常清洁'), ('DISINFECTION', '消毒'), ('DEEP_CLEAN', '深度清洁'), ('WASTE_REMOVAL', '粪便清理')], default='DAILY', max_length=30, verbose_name='清洁类型')),
                ('cleaning_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='清洁时间')),
                ('duration_minutes', models.IntegerField(default=0, verbose_name='耗时(分钟)')),
                ('disinfectant_used', models.CharField(blank=True, max_length=100, verbose_name='使用消毒剂')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('cleaner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_records', to=settings.AUTH_USER_MODEL, verbose_name='清洁人')),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cleaning_records', to='api.pen', verbose_name='栏区')),
            ],
            options={
                'verbose_name': '清洁记录',
                'verbose_name_plural': '清洁记录',
                'ordering': ['-cleaning_time'],
            },
        ),
        migrations.AddIndex(
            model_name='inspectionrecord',
            index=models.Index(fields=['pen', 'inspection_time'], name='api_inspect_pen_id_a3edcd_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrecord',
            index=models.Index(fields=['inspection_time'], name='api_inspect_inspect_049c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionitemvalue',
            index=models.Index(fields=['record', 'inspection_item'], name='api_inspect_record__f79ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['pen', 'incident_time'], name='api_inciden_pen_id_201134_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'incident_time'], name='api_inciden_status_4e35f4_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_time'], name='api_inciden_inciden_66deed_idx'),
        ),
        migrations.AddIndex(
            model_name='feedingrecord',
            index=models.Index(fields=['pen', 'feeding_time'], name='api_feeding_pen_id_df5b56_idx'),
        ),
        migrations.AddIndex(
            model_name='feedingrecord',
            index=models.Index(fields=['feeding_time'], name='api_feeding_feeding_c9437b_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningrecord',
            index=models.Index(fields=['pen', 'cleaning_time'], name='api_cleanin_pen_id_4a53fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningrecord',
            index=models.Index(fields=['cleaning_time'], name='api_cleanin_cleanin_f8ab0e_idx'),
        ),
    ]
