# Generated by Django 4.2.7 on 2026-06-11 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentupdate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间'),
        ),
    ]
