# Generated by Django 4.2.7 on 2026-06-11 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_dailysnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthScoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension_key', models.CharField(choices=[('inspection_abnormal', '巡检异常数量'), ('open_incidents', '未处理异常事件'), ('feeding_completion', '喂养完成情况'), ('cleaning_completion', '清洁完成情况'), ('capacity_ratio', '存栏容量占比')], max_length=50, unique=True, verbose_name='评分维度')),
                ('weight', models.FloatField(default=20.0, verbose_name='权重(%)')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '健康评分维度配置',
                'verbose_name_plural': '健康评分维度配置',
                'ordering': ['sort_order', 'dimension_key'],
            },
        ),
        migrations.CreateModel(
            name='HealthScoreRiskThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('EXCELLENT', '优秀'), ('GOOD', '良好'), ('NORMAL', '一般'), ('WARNING', '警告'), ('DANGER', '危险')], max_length=20, unique=True, verbose_name='风险等级')),
                ('min_score', models.FloatField(verbose_name='最低分(含)')),
                ('max_score', models.FloatField(verbose_name='最高分(不含)')),
                ('color', models.CharField(default='#00FF00', max_length=20, verbose_name='显示颜色')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '风险等级阈值配置',
                'verbose_name_plural': '风险等级阈值配置',
                'ordering': ['-min_score'],
            },
        ),
        migrations.CreateModel(
            name='HealthScoreRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_date', models.DateField(verbose_name='评分日期')),
                ('total_score', models.FloatField(default=100.0, verbose_name='总分')),
                ('base_score', models.FloatField(default=100.0, verbose_name='基础分')),
                ('deduction', models.FloatField(default=0.0, verbose_name='总扣分')),
                ('addition', models.FloatField(default=0.0, verbose_name='总加分')),
                ('risk_level', models.CharField(choices=[('EXCELLENT', '优秀'), ('GOOD', '良好'), ('NORMAL', '一般'), ('WARNING', '警告'), ('DANGER', '危险')], default='GOOD', max_length=20, verbose_name='风险等级')),
                ('inspection_abnormal_score', models.FloatField(default=0.0, verbose_name='巡检异常扣分')),
                ('open_incidents_score', models.FloatField(default=0.0, verbose_name='未处理事件扣分')),
                ('feeding_completion_score', models.FloatField(default=100.0, verbose_name='喂养完成得分')),
                ('cleaning_completion_score', models.FloatField(default=100.0, verbose_name='清洁完成得分')),
                ('capacity_ratio_score', models.FloatField(default=100.0, verbose_name='存栏容量得分')),
                ('inspection_abnormal_count', models.IntegerField(default=0, verbose_name='巡检异常数量')),
                ('open_incidents_count', models.IntegerField(default=0, verbose_name='未处理事件数量')),
                ('feeding_completion_rate', models.FloatField(default=0.0, verbose_name='喂养完成率(%)')),
                ('cleaning_completion_rate', models.FloatField(default=0.0, verbose_name='清洁完成率(%)')),
                ('capacity_ratio', models.FloatField(default=0.0, verbose_name='存栏容量占比(%)')),
                ('is_calculated', models.BooleanField(default=False, verbose_name='是否已计算')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='计算时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='api.pen', verbose_name='栏区')),
            ],
            options={
                'verbose_name': '栏区健康评分记录',
                'verbose_name_plural': '栏区健康评分记录',
                'ordering': ['-score_date', 'pen__code'],
            },
        ),
        migrations.CreateModel(
            name='HealthScoreInspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_per_abnormal', models.FloatField(default=5.0, verbose_name='每次异常扣分')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inspection_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_configs', to='api.inspectionitem', verbose_name='巡检项')),
            ],
            options={
                'verbose_name': '评分巡检项配置',
                'verbose_name_plural': '评分巡检项配置',
                'ordering': ['inspection_item__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HealthScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('DEDUCTION', '扣分'), ('ADDITION', '加分'), ('RECOVERY', '恢复加分')], max_length=20, verbose_name='类型')),
                ('source_type', models.CharField(choices=[('inspection_abnormal', '巡检异常'), ('open_incident', '未处理异常事件'), ('incident_resolved', '异常事件解决'), ('feeding_incomplete', '喂养未完成'), ('cleaning_incomplete', '清洁未完成'), ('capacity_abnormal', '存栏容量异常'), ('manual_adjust', '人工调整')], max_length=30, verbose_name='来源类型')),
                ('score_value', models.FloatField(default=0.0, verbose_name='分值')),
                ('description', models.CharField(max_length=500, verbose_name='描述')),
                ('source_id', models.IntegerField(blank=True, null=True, verbose_name='关联源记录ID')),
                ('rectification_status', models.CharField(default='pending', max_length=50, verbose_name='整改状态')),
                ('rectified_at', models.DateTimeField(blank=True, null=True, verbose_name='整改时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_details', to='api.incident', verbose_name='关联异常事件')),
                ('inspection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_details', to='api.inspectionitem', verbose_name='关联巡检项')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_details', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('score_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.healthscorerecord', verbose_name='评分记录')),
            ],
            options={
                'verbose_name': '健康评分明细',
                'verbose_name_plural': '健康评分明细',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='healthscorerecord',
            index=models.Index(fields=['score_date', 'pen'], name='api_healths_score_d_a117b5_idx'),
        ),
        migrations.AddIndex(
            model_name='healthscorerecord',
            index=models.Index(fields=['risk_level'], name='api_healths_risk_le_bcb0a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='healthscorerecord',
            constraint=models.UniqueConstraint(fields=('score_date', 'pen'), name='unique_daily_pen_score'),
        ),
        migrations.AddIndex(
            model_name='healthscoredetail',
            index=models.Index(fields=['score_record'], name='api_healths_score_r_b2a1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='healthscoredetail',
            index=models.Index(fields=['source_type'], name='api_healths_source__f192a3_idx'),
        ),
        migrations.AddIndex(
            model_name='healthscoredetail',
            index=models.Index(fields=['rectification_status'], name='api_healths_rectifi_f6ccf3_idx'),
        ),
    ]
